// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.spotify.com',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  client_id : '366426de773243b6b429568267c85c3c',
  response_type : 'token',
  redirect_uri : 'http%3A%2F%2Fbitsangular.afar.systems%2Fhome',
  scope : 'user-read-private%20user-read-email',
  state : '123',
};
